name: Docker Image CI

on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag secondapp:$(date +%s)
